version: '3'
services:
  app:
    build: ./user-management
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:13
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
  redis:
    image: redis:6