version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"  # Map port 8080 in the container to port 8080 on the host
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: authdb
  redis:
    image: redis:6
    ports:
      - "6379:6379"